#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-data.dkrz.de - 2026/10/04 17:14:15
# Search URL: https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp585.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp245.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp245.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp585.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp245.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp585.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp585.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp245.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Omon.uo.gn.v20200909|esgf3.dkrz.de,CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp245.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp585.r1i1p1f1.Omon.vo.gn.v20190710|esgf3.dkrz.de,CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp245.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp585.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de,CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.r1i1p1f1.Omon.chl.gn.v20190710|esgf3.dkrz.de'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc' 'SHA256' '7f652c2c07d022a3e5115f154fddcf53059edb03feb138ed06db0bdf82e0e991'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc' 'SHA256' 'f852c6d5e0db473de286fc3f60bef0df845d682e254030b451b5e2c602737af0'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc' 'SHA256' 'b8e95dcb531a61478bb624b9a8802bc4b05fcb17ab5d67257ba3d1aeb7ff064f'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc' 'SHA256' 'f5641e49ad7cb4f2539c4586e16d00e0a1df8c8140a3cd2cf1c00c82dd5e1863'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc' 'SHA256' '0f3d6c07d79867edd0af74b731c5ce6fa8df00f5d3baf864b4c35beec69bc865'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc' 'SHA256' '4720abfb16082ac2afaf6e92e5c6fc91c96163dafbaf24f0dedd94d1bd1f55bb'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc' 'SHA256' '4f9fb7d6dcc14774274d78456089c921bc7c26703f7882fecf43499418be5828'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc' 'SHA256' 'c19721b13ab5663a026c832b500d78c93315f24e207fa246723e3d3dbc8a233a'
'chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' '29f441dcc82bef802ad810cf9549685b9979c411759f60f598942ec31f54416d'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc' 'SHA256' 'b8d114db3801bbb8c9cf9459656e0d1a30296421ee5939c29d33defcb5049dea'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc' 'SHA256' '32a9e26585772db674c7e67eedc5cd52e7c238bc8fe4cc50a692155047ec6392'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc' 'SHA256' '56b9e208ab04d55f824b6883724baea784fa4bde27812156c89bae3e8fc1bcb7'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc' 'SHA256' 'ad6d1ef8cbdec20cd314816efea929fdbb5e871f1e43b487bc052502d48bdb86'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc' 'SHA256' 'e5dc366cebe3b947ac158a72510436f74918d59728edcfcbcea137a1424efa91'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc' 'SHA256' '0af17e005ddacac04d24cb67bdb1b6e1fc5a4791dfb9d3a69a6b6f6219febe1c'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc' 'SHA256' '9c411d802ee90782616185d350562353e824de299444d65ee8eaf34b37cc618a'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc' 'SHA256' '6ed1f6e283124df6d68eed9ca3494ad079397e3dc03c1561464bfb2c8db119af'
'uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' '9aa2e3a5b2d5a986f832e60bf3a8a3789ff1f010e0c0e3bfdf58fffc1717a5f4'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_185001-186912.nc' 'SHA256' '6bac64d09675efeb8f76c5a0f5e3fc24a83eb7608465cdb6822c41bc9971f0c2'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_187001-188912.nc' 'SHA256' 'f6059b641dfaade0255015c1a931b9e2f4992d429f62294afc24d7dbbc125f9f'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_189001-190912.nc' 'SHA256' '480c8f0e6507e01b76193509b4d737206faae11456916f38788b76cf327956dd'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_191001-192912.nc' 'SHA256' 'bcb05c80c5e0cf7b12a1f7a0cbec281117bcb9627fc8e40937ef7a3f7f967f48'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_193001-194912.nc' 'SHA256' '5133192ffe4268f5090de0ddfd2d8b70bb6aa1413917740055605781dd71ecff'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_195001-196912.nc' 'SHA256' '13026ab57b6f0eca0ea5e4e09d506a67aac5a24fb39dc1951a789668efbf7583'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_197001-198912.nc' 'SHA256' '8c106aebd925a908655a489496ea48a0e5cdab4908cb90296faaad4f52cb6cf6'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_199001-200912.nc' 'SHA256' '4e04757e02a7598634d364fbc686021a4d4d5122cc8d5f6be62413c610128127'
'vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' 'e8d042c39fc9bc052181aa5bad08f30900357d34e20c4857f4bb5d23968fdb0f'
'chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '513893bdd8ec138b9f96e27fbc7384c592e46a5097ac8294bc912b66985f0fcf'
'chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_203501-205412.nc' 'SHA256' 'a127ea879634a694b988374438496ac4267c637ee20fd79fe4eb4e5d248d3956'
'chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '6bdec6eb891631b14c1ac97948e15785045ef601afe64258456e68b31cf86f84'
'chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_207501-209412.nc' 'SHA256' 'a4a9b3c747688b9427f2efe0d2df1f252855928e165fe94847d0d8c05a617cdf'
'chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '8cd33012ef763a5ed906dc8595a573cc17bc99cc6f447b743dfbeddd1c2e1943'
'uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_201501-203412.nc' 'SHA256' 'f702537b52bf5b5fc8b8c06aecc1b81cfcdc948046108100b466d9358e109f44'
'uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '73f1de8a8241a4a488b6707525382f346d8194f87a9006e1a3f56fecf68bbe19'
'uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_205501-207412.nc' 'SHA256' 'd9fdadb1134a96839f5d94fcca22e1ef921e3185d3532da5009991cf118c1d93'
'uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '24db4a037cd6b1c5ce682273fbf020eafa537f69014dfd95ac65ed09409af7e9'
'uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '016e6abd175507213b369f71c6b560200d1d35ed0579ca0754eb0a52e845278a'
'vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '111da27c8350f7ac6238a6a4bed65f70d83137c303ed812e4c9e9c95c48c3280'
'vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_203501-205412.nc' 'SHA256' 'adaa31100111aef28a3a5d9f2a1b04ee89c619cc35c52072282bb6d930d9737a'
'vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '92736a354c06a7dd0dcc667972d367985d3b2c12ed39a6bdcc9a5ffbcab648bb'
'vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '7ee5977d7e8322d12a12d5f9a4b294ee3765cf749f00f90ccdd4b286edf648e9'
'vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp126/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp126_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '0b6025ec9ed729e835cf3e17cf168191b08aaa77a8957726c903d28c1a7bf5b9'
'chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '02f0cae7786e5128a61d6fcb5231022f4114a537add6354b4f176f1eec1fe146'
'chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '7f86a53280a6e9d3089e254eda052decfc6dc22ceab481b45662e2eaa05e2bef'
'chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '8c40accb91a6481ef7cc320f6217811a4d2533e890a7fcb937bca9283b02d2ba'
'chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_207501-209412.nc' 'SHA256' 'd7227c74c86c1462b3cd9e176868d9bc0db34aaffd41ea11a0de7bc3c57b0467'
'chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_209501-210012.nc' 'SHA256' 'd984ecc8a35fec534bbb3660e854ad11de049da6f1c5f54e175ae9a6c1e9d6e7'
'uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '0495ecf66ba3ac350b896885c138f9ddbb02d317fd92beb44457fcb3c0464ce8'
'uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '83aaeb132f0214e75faaff9a5a3489f7fdf34f4b5c5822df9c01a93e8153faf6'
'uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_205501-207412.nc' 'SHA256' 'daa035e79317201fc15c4a1a341bcfabf4810723c8b96a9f7cf6949eebee074f'
'uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_207501-209412.nc' 'SHA256' 'a6c377aabfef240c8e7934e0a06f2e96d0c82d9454754463c8f87234ec0b5ab0'
'uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_209501-210012.nc' 'SHA256' 'a134044df2c544dd917ff46d32f38ada6e6059c594ce1ded74ca7536ddc3cceb'
'vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '19c38daa4761636ca1b22d6d1699900242f1c807e8a31a289e018f6fbe1fd4bf'
'vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '391da63aeedc62dff803ec353d1eb3deab494557ecd62983fade824c4d294250'
'vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_205501-207412.nc' 'SHA256' 'ac52bdc38527de4c301cc2f0280e6c99ded7a4e5617f1e175aaeca04cbe9cdf3'
'vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '686cedec66103af31a481c0e458ffc622ce0b43f37e5a5cb5c4506010e6cc286'
'vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp245/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp245_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '5778ab37091a0d6c6b60e64b3995cb867fbdfd176587164a9d01f074c16e698d'
'chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_201501-203412.nc' 'SHA256' 'ab8289f43ccd0e69009e3f1e0da0280240ee816d5635d6872a7e679ae01823db'
'chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_203501-205412.nc' 'SHA256' 'e12a47e197981cfd5055c3222610b921a4278874631a1b252da34cb6f837ab2f'
'chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '4f68f9654c1bf4c7166258b1c3968de36803a3344c5a500a96a0d3047f4403d6'
'chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_207501-209412.nc' 'SHA256' 'f1d855bf2bfdafe56422fef267d3b17aec380db701c6902f7fb56820ea4ac78f'
'chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_209501-210012.nc' 'SHA256' 'df76e7214dce0b562086143c35099bbedd36012b5acb954770bc32c026d67cf1'
'uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '2974067e88b7a4720afc9cba2013ad7b57173e66b02d72bc2aaa677aee1f6205'
'uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '2353d80a6aa62b5e3101490a65ef060d3c2edfc32c167ec23d9c1b18efb32fb7'
'uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_205501-207412.nc' 'SHA256' 'dbbc7cf579b8f15ccea9c72c4979c52dcf05cbf391a72f77e73855ecdac846f0'
'uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '852468904c903d92b0323760dfa395504e3cb07c0d88517ca42bcda53d635371'
'uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '242f2d1e672f82e792dce8c4abbb4ff93805244254c2e9ea8b821e99fb48f298'
'vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '383e2c4970e58dae7a1651e1730ebbf94a7fe0d28b7233039e842e7eb9a92b5f'
'vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '7584a0942e5a5d79fa4ec5b8f02288ff2898994df8f7cf9be64962a70ec8a10a'
'vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '198b37b383fd6dd721081ca6d5fdff27ea821b127746154314fb52b0bf05a89e'
'vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_207501-209412.nc' 'SHA256' 'eb2e5ec9c6eff81f7718a23cd1bdced8f50be1d321d2afe25e7c61008b146bfb'
'vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp370/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp370_r1i1p1f1_gn_209501-210012.nc' 'SHA256' 'bc8d08bc39cc0dc8a3bbde48ddade71ebd886b6964c2c5f766259842be62f8cd'
'chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc' 'SHA256' 'b8acb00575efbdfddfa745670edc45bb25b2fcbc5cf5af8c79e08054b10c9719'
'chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc' 'SHA256' 'b776fdd2ab58a161276ae0139a66fe297d3ce7fa65c05f53340de20b01ea2d13'
'chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '9b6102cffefd7e7465b34ef4345dee1135c5459ba6b8b96380d4542b0cf16b35'
'chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '429cadca9b3def75b73378490f1ad0394b1c98af665527a85e320113d34a02a6'
'chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/chl/gn/v20190710/chl_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '818b18e113c8fe7a021e10d7aa0eb681ccf5173e96aad9234fac6149b7fbf357'
'uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc' 'SHA256' 'd40c268a97abaf7297f8dd5860c5badd356b19625f760470cd0c384fa0622a64'
'uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '8cd7b9c6a3d2d35a9b70e8a87aa940ce2a12c19a43fda527539aed091d0d0320'
'uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '40b04a510a4c0f7536cf5f884fdcd013801417a47500905a1fb86d5327064791'
'uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '92c882fd9c2a5a752992b8cdf4ce36ca2573555b50fa72d6bf0df3d1096191d2'
'uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/uo/gn/v20200909/uo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc' 'SHA256' 'e7a1d5b1031aaee6ea93eb5e2db7873680a120ef541cfc577a86e3a7ad296863'
'vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '9dbd040a7bd34f6a9362c48492b4ab543ce8e95234ea8ff5133cac35f60a1d73'
'vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '600d606e709ff5df9171d40ce41ea4631710334b318dbe49fb4525205a04de2d'
'vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '0b159eb1ccccf62f884084420c5b12b0831defe622b8d960c8dc6e27b66b64b6'
'vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '4f1a3fcee106d29da66cb9cac02c85bd215e72abb094035f1083c08ad71f6325'
'vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc' 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Omon/vo/gn/v20190710/vo_Omon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '58278844dc52b44196f8221418811e04b4dcdb959f62cf1cabed98312685cbe0'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 87 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
